### ISSUE TITLE
Ability to remove all health (kill) a character in one click

### ISSUE THREAD

**Issue by sparetomato** [shafeen/swdestinystation-task-board#14]
When the opponent god-rolls a blowout, can you make it so that the character health is reduced to 0 in one click, instead of having to click -1 health each time?

**Comment by shafeen** [comment]
Damage can now be assigned in 1/2/3 health increments, which should cut down on the number of times you should have to click to damage and "kill" a character. This should reduce the need to have a dedicated "kill character" button.
