### ISSUE TITLE
Add a shortcut ability to roll-off at the start of the game

### ISSUE THREAD

**Issue by sparetomato** [shafeen/swdestinystation-task-board#17]
Could you add a function where in a single click, all character dice are rolled to determine which 'player' chooses the battlefield please?

At present, I believe the only way to do this is manually activate each character prior to the start of the game.

Although ultimately it is the player who is determining the battlefield to use, it is helpful to evaluate how likely you are to win the roll-off with a given team against a particular team

**Comment by shafeen** [comment]
Adding a way to easily see a player's/opponent's chances of winning the initial **"roll-off"** is also probably a good idea at the start of the match (before a battlefield is chosen).

**Comment by shafeen** [comment]
The Player/Opponent "Actions" menus should now have the option to "Activate all Characters". This can be used to perform the initial "roll-off".
