### ISSUE TITLE
Add the ability to add/remove shields and damage in one click 

### ISSUE THREAD

**Issue by aphillippe** [shafeen/swdestinystation-task-board#18]
It's a bit tedious clicking to get the context menu up then moving the mouse to (hopefully) the correct option then clicking, 8 times in a row. I would suggest a plus button on the right of each damage/shield bar and a minus button in the left. While we're there, I would suggest changing the damage bar so it shows damage taken rather than health remaining. 1) this better fits the mechanics of the game and 2) the plus buttons can both then be placed on the right hand side (it would be weird to have a plus button in the right to add damage that then moves the 'health' bar to the left

**Comment by shafeen** [comment]
Added more ui improvements, particularly for damaging & healing via context menus.
You can now do 1-3 damage or heal per click, making it easier to assign damage to (or heal) characters.
